services:
  web:
    build: .
    ports:
      - "5050:5000"
    environment:
      FLASK_APP: "app"
      FLASK_ENV: "development"
      DATABASE_URL: "postgresql://n5_test:n5_test_password@db:5432/n5_test_db"
      JWT_SECRET_KEY: "n5_jwt_secret"
    volumes:
      - .:/app
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: n5_test
      POSTGRES_PASSWORD: n5_test_password
      POSTGRES_DB: n5_test_db
    ports:
      - "5433:5432"
