services:
  web:
    image: joaz/n5-traffic-web:latest
    ports:
      - "5050:5000"
    environment:
      FLASK_APP: "app"
      FLASK_ENV: "production"
      DATABASE_URL: "postgresql://n5_test:n5_test_password@db:5432/n5_test_db"
      JWT_SECRET_KEY: "n5_jwt_secret"
    depends_on:
      - db

  db:
    image: joaz/n5-traffic-db:latest
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: n5_test
      POSTGRES_PASSWORD: n5_test_password
      POSTGRES_DB: n5_test_db
